### ISSUE TITLE
HiDPI screens

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/peculiarpointer#1]
It works great but we need to tweak the CSS a bit to make it looks great on HiDPI screens:

```
 .cursor {
     cursor: url("cursor.png") 0 0, pointer; /* Legacy */
     cursor: url("cursor.svg") 0 0, pointer; /* FF */
     cursor: -webkit-image-set(url("cursor.png") 1x, url("cursor@2x.png") 2x) 0 0, pointer; /* Webkit */
 }
```

Also we probably need to let them upload the 2x version (at least a 64px image) and we'll make the 1x for them.

**Comment by Mamaduka** [comment]
> Also we probably need to let them upload the 2x version (at least a 64px image) and we'll make the 1x for them.

Generating the 1x version won't be an easy task. Will require an extra step (like with Dapper Desktop) and some major logic changes.

Maybe we should recommend [Save SVG](https://wordpress.org/plugins/safe-svg/) plugin for  `SVG` icons and better quality in plugin readme?

Looks like browsers also ignore large SVG icons, instead of scaling them down. So I think we should recommend 32x32px for SVGs as well.

**Comment by nickhamze** [comment]
So the way it works now if I enable the plugin could I use SVGs? If that's the case I think that's good enough and I'll offer both versions in addition to letting people know about the plugin.

**Comment by Mamaduka** [comment]
@nickhamze That's correct. The plugin adds SVG uploads feature to WP, so you can use SVG with our block and anywhere else.

**Comment by nickhamze** [comment]
Sounds good. Put together a v1 for me and I'll prep the readme file and get it submitted later today.

**Comment by Mamaduka** [comment]
Created release with a custom build.

**Comment by nickhamze** [comment]
Ok, after I little testing and searching I found out that even SVGs are blurry on HIDPI devices. I guess it takes the SVG and rasterizes it at 1x.

The only solution is to use the above snippet. 

I did have a thought. What if we made the 1x and the 2x image the same image. I'll tell people to use 64px images instead so they look the right size on HIDPI devices. The side effect will be that on non-HIDPI devices the cursors will be twice as big but I'm ok with that. I think the people that use this will hipsters anyways who have the nice retina devices. 

What do you think?

**Comment by nickhamze** [comment]
The more I think about it, the more I think we probably need to do this right if we are going to do it at all, even if it costs more. 

Please forgive me is this is a dumb question but couldn't we just limit them to only uploading a 64x64 PNG and then we'll use this PHP function to add a custom image size (the 1x 32x32 version):
https://developer.wordpress.org/reference/functions/add_image_size/

Can't we then get all the image sizes from the media object:
https://github.com/WordPress/gutenberg/issues/8425#issuecomment-491541914

**Comment by Mamaduka** [comment]
@nickhamze I think we should go with the first option since it has only a minor side effect. Ask users to upload 64px images and use the snippet above.

Issues with second options:
* We can't limit users to only upload 64x64px images in Gutenberg Media flow.
* `add_image_size()` will generate 32x32px image for every upload. There's no way to limit this only for our block. This was the main reason I used the resized button in "Dapper Desktop"
* WordPress can't resize SVG files.

**Comment by nickhamze** [comment]
ok, let's do option 1.

**Comment by Mamaduka** [comment]
@nickhamze update the code and release build.
